### ISSUE TITLE
Extension broke

### ISSUE THREAD

**Issue by janmonschke** [spadgos/sublime-require-helper#7]
Every time I try to use the extension Sublime freezes. The console gives me the following message:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "require_helper in /Users/(...)/Sublime Text 3/Installed Packages/Require Helper.sublime-package", line 150, in run
KeyError: 'require'
```

Restarting Sublime and re-installing the extension didn't help.

**Comment by reebayroo** [comment]
Sublime 3 
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "require_helper in /Users/..../Library/Application Support/Sublime Text 3/Installed Packages/Require Helper.sublime-package", line 150, in run
KeyError: '});'
